### ISSUE TITLE
Add type definitions for new methods in Ruby 2.7

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#2390]
### Problem

Ruby 2.7 comes out on Wednesday and adds some new methods to core classes. Currently, Sorbet doesn't have type definitions for any of these.

### Proposed solution

Add type signatures for all the new methods in Ruby 2.7 :)

**New Methods:**

- [x] `Array#intersection` [Feature #16155](https://bugs.ruby-lang.org/issues/16155)
- [x] `Array#minmax` (faster implementation than `Enumerable#minmax`) [Bug #15929](https://bugs.ruby-lang.org/issues/15929)
- [ ] `Complex#<=>` [Bug #15857](https://bugs.ruby-lang.org/issues/15857)
- [x] `Enumerable#filter_map`. [Feature #15323](https://bugs.ruby-lang.org/issues/15323)
- [x] `Enumerable#tally` [Feature #11076](https://bugs.ruby-lang.org/issues/11076)
- [ ] `Enumerator.produce` [Feature #14781](https://bugs.ruby-lang.org/issues/14781)
- [ ] `Enumerator::Lazy#eager` [Feature #15901](https://bugs.ruby-lang.org/issues/15901)
- [ ] `Enumerator::Yielder#to_proc` [Feature #15618](https://bugs.ruby-lang.org/issues/15618)
- [ ] `Fiber#raise` [Feature #10344](https://bugs.ruby-lang.org/issues/10344)
- [ ] `FrozenError#receiver` [Feature #15751](https://bugs.ruby-lang.org/issues/15751)
- [ ] `GC.compact` [Feature #15626](https://bugs.ruby-lang.org/issues/15626)
- [ ] `IO#set_encoding_by_bom` [Bug #15210](https://bugs.ruby-lang.org/issues/15210)
- [x] `Module#const_source_location` [Feature #10771](https://bugs.ruby-lang.org/issues/10771)
- [x] `Module#ruby2_keywords` [Bug #16154](https://bugs.ruby-lang.org/issues/16154)
- [x] `Proc#ruby2_keywords` [Feature #16404](https://bugs.ruby-lang.org/issues/16404)
- [x] `Range#minmax` (faster implementation than `Enumerable#minmax`) [Bug #15807](https://bugs.ruby-lang.org/issues/15807)
- [x] `Symbol#start_with?` [Feature #16348](https://bugs.ruby-lang.org/issues/16348)
- [x] `Symbol#end_with?` [Feature #16348](https://bugs.ruby-lang.org/issues/16348)
- [x] `Time#ceil` [Feature #15772](https://bugs.ruby-lang.org/issues/15772)
- [x] `Time#floor` [Feature #15653](https://bugs.ruby-lang.org/issues/15653)
- [ ] `UnboundMethod#bind_call` [Feature #15955](https://bugs.ruby-lang.org/issues/15955)

**Changed Methods:**

- [ ] `Comparable#clamp` now accepts a Range argument. [Feature #14784](https://bugs.ruby-lang.org/issues/14784)
- [ ] `Dir.glob` and `Dir.[]` no longer allow NUL-separated glob pattern. Use Array instead. [Feature #14643](https://bugs.ruby-lang.org/issues/14643)
- [ ] `Integer#[]` now supports range operation. [Feature #8842](https://bugs.ruby-lang.org/issues/8842)
- [ ] `Module#autoload?` now takes an `inherit` optional argument, like as `Module#const_defined?`. [Feature #15777](https://bugs.ruby-lang.org/issues/15777)
- [ ] `ObjectSpace::WeakMap#[]=` now accepts special objects as either key or values. [Feature #16035](https://bugs.ruby-lang.org/issues/16035)
- [ ] `Time#inspect` is separated from `Time#to_s` and shows its sub second. [Feature #15958](https://bugs.ruby-lang.org/issues/15958)

**Comment by elliottt** [comment]
Thanks for aggregating all of these!

**Comment by greggroth** [comment]
I don't see it on the list, but there's also a type-check failure when using the new pattern matching `case`/`in` tokens:

Using this as an example:

```ruby
case {}
in { a: }
  true
else
  false
end
```

I get the following type-checking errors:

```
./example.rb:2: unexpected token kIN https://srb.help/2001
     2 |in { a: }
        ^^

example.rb:2: unexpected token kIN https://srb.help/2001
     2 |in { a: }
        ^^
Errors: 6
```

**Comment by paracycle** [comment]
@greggroth Super late reply, but that is a problem with the Sorbet parser not knowing about the new language features, whereas this issue tracks the definitions for the method additions/changes.

The 2.7 syntax update is tracked here: https://github.com/sorbet/sorbet/issues/2900 and there is already good progress for it. However, I am not sure if we will be able to support full type-checking for pattern matching at this time, though Sorbet will not raise parse errors at least.

**Comment by Morriar** [comment]
@connorshea I think you can update this list:

* [x] `Complex#<=>`: https://github.com/sorbet/sorbet/pull/4227
* [x]  `UnboundMethod#bind_call`: https://github.com/sorbet/sorbet/pull/4126
* [x] `Comparable#clamp`: https://github.com/sorbet/sorbet/pull/4222
* [x] `Integer#[]`: https://github.com/sorbet/sorbet/pull/4228

**Comment by Morriar** [comment]
As of today you can also close:

* [x] `Enumerator.produce`: https://github.com/sorbet/sorbet/pull/6020
* [x] `Enumerator::Lazy#eager`: https://github.com/sorbet/sorbet/pull/6020
* [x] `Enumerator::Yielder#to_proc`: https://github.com/sorbet/sorbet/pull/6020
* [x] `Fiber#raise`: https://github.com/sorbet/sorbet/pull/6021
* [x] `FrozenError#receiver`: https://github.com/sorbet/sorbet/pull/6022
* [x] `IO#set_encoding_by_bom`: https://github.com/sorbet/sorbet/pull/6023
* [x] `Module#autoload?`: https://github.com/sorbet/sorbet/pull/6025

Not in the list but I also handled:

* [x] `Object#clone(freeze: true)`: https://github.com/sorbet/sorbet/pull/6028
* [x] `Set#initialize_clone`: https://github.com/sorbet/sorbet/pull/6030
* [x] `Warning#warn`: https://github.com/sorbet/sorbet/pull/6029

And finally I don't think we can do anything about:

* [x] `Dir.glob` & `Dir.[]`: those methods are overloaded so we can't precise the keyword parameters
* [x] `Time#inspect` is separated from `Time#to_s`: doesn't impact signatures

I think we can close this issue. Feel free to reopen if I missed one.

**Comment by jez** [comment]
Thanks!!!
